services:
  todo-app:
    build: .
    container_name: todo-app
    restart: on-failure
    volumes:
      - ./config:/config
      - ./migrations/postgres:/migrations/postgres
      - ./internal/html/templates:/internal/html/templates
      - ./uploads/image_avatar:/uploads/image_avatar
    environment:
      - "WN_POSTGRES_HOST=postgres"
      - "WN_REDIS_HOST=redis:6379"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - '8082:8082'
  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      env_file:
        .env
      POSTGRES_USER: ${WN_POSTGRES_USER}
      POSTGRES_PASSWORD: ${WN_POSTGRES_PASSWORD}
      POSTGRES_DB: ${WN_POSTGRES_DATABASE}
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    env_file:
      .env
    command: redis-server --requirepass ${WN_CONFIG_REDIS_PASSWORD}
    volumes:
      - ./volumes/redis-data:/var/lib/redis
    restart: unless-stopped
volumes:
  redis-data:
    driver: local