postgres:
  host: localhost
  port: 5432
  user: example
  password : example
  database: example

logger:
  logger_lvl: error

serve:
  statics: true
  Prefork: true

middleware:
  AbsoluteCookieTimeout: 24h