postgres:
  host: localhost
  port: 5432
  user: example
  password : example
  database: example

logger:
  level: error

server:
  statics: false
  Prefork: true
  idleTimeout: 2h
  absoluteCookieTimeout: 24h

config:
  server:
    host: "127.0.0.1"
    port: 8082
  redis:
    host: "127.0.0.1"
    port: 6379
    password: example